### ISSUE TITLE
Example code issue

### ISSUE THREAD

**Issue by lshahar** [golismero/openvas_lib#14]
while trying to run example code got exception
```
from openvas_lib import VulnscanManager, VulnscanException

try:
    scanner = VulnscanManager(HOST, USER, PASSWORD, PORT, TIMEOUT)
except VulnscanException as e:
    print("Error:")
    print(e)

```

> 
> Traceback (most recent call last):
>   File "vas_poc.py", line 35, in <module>
>     my_launch_scanner()
>   File "vas_poc.py", line 19, in my_launch_scanner
>     manager = VulnscanManager("localhost", "admin", "admin",4433)
>   File "/usr/lib/python2.7/site-packages/openvas_lib/__init__.py", line 497, in __init__
>     self.__manager = get_connector(host, user, password, port, m_time_out, ssl_verify)
>   File "/usr/lib/python2.7/site-packages/openvas_lib/common.py", line 73, in get_connector
>     manager = ConnectionManager(host, username, password, port, timeout, ssl_verify)
>   File "/usr/lib/python2.7/site-packages/openvas_lib/common.py", line 149, in __init__
>     self._connect()
>   File "/usr/lib/python2.7/site-packages/openvas_lib/common.py", line 200, in _connect
>     self._authenticate(self.__username, self.__password)
>   File "/usr/lib/python2.7/site-packages/openvas_lib/common.py", line 228, in _authenticate
>     self.make_xml_request(m_request)
>   File "/usr/lib/python2.7/site-packages/openvas_lib/common.py", line 378, in make_xml_request
>     raise ValueError('Missing status property in response')
> ValueError: Missing status property in response
>

**Comment by XTpeeps** [comment]
i have the same question.  did u fixed this?

**Comment by Flokiv** [comment]
try it with out the PORT and TIMEOUT
VulnscanManager(HOST, USER, PASSWORD)
https://github.com/golismero/openvas_lib/blob/master/openvas_lib/__init__.py#L538

**Comment by ksakthii001** [comment]
Hi, 

I am able to recreate the problem. If we reference a port number that is already in use, we hit this problem.  Please check below for errors.

$ sudo python openvas.py
Traceback (most recent call last):
  File "openvas.py", line 35, in <module>
    my_launch_scanner()
  File "openvas.py", line 19, in my_launch_scanner
    manager = VulnscanManager("localhost", "admin", "admin", 443)
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/__init__.py", line 497, in __init__
    self.__manager = get_connector(host, user, password, port, m_time_out, ssl_verify)
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/common.py", line 73, in get_connector
    manager = ConnectionManager(host, username, password, port, timeout, ssl_verify)
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/common.py", line 152, in __init__
    self._connect()
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/common.py", line 203, in _connect
    self._authenticate(self.__username, self.__password)
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/common.py", line 231, in _authenticate
    self.make_xml_request(m_request)
  File "/home/ksakthii001/github/openvas_lib/openvas_lib/common.py", line 381, in make_xml_request
    raise ValueError('Missing status property in response')
ValueError: Missing status property in response

$ netstat -anp | grep LISTEN         
tcp6       0      0 :::443                  :::*                    LISTEN      -              
tcp6       0      0 :::9390                 :::*                    LISTEN
