### ISSUE TITLE
scanner.get_results: TypeError: Expected string, got <type 'NoneType'> instead 

### ISSUE THREAD

**Issue by anandtiwarics** [golismero/openvas_lib#18]
While getting result using get_results below error encounter.

Traceback (most recent call last):
  File "openvas.py", line 11, in <module>
    openvas_results = scanner.get_results(SCAN_ID)
  File "C:\Python27\lib\site-packages\openvas_lib\__init__.py", line 728, in get_results
    m_response = self.__manager.get_report_xml(self.__task_report_id)
  File "C:\Python27\lib\site-packages\openvas_lib\ompv4.py", line 589, in get_report_xml
    raise TypeError("Expected string, got %r instead" % type(report_id))
TypeError: Expected string, got <type 'NoneType'> instead

**Comment by codebrk** [comment]
I am having the same problem
