### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by OguzBey** [golismero/openvas_lib#31]
`Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openvas_lib import VulnscanManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oguzbey/Desktop/virtualEnviroments/openvasEnv/lib/python3.7/site-packages/openvas_lib/__init__.py", line 373
    elif l_tag == "severity":
                            ^
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by OguzBey** [comment]
Check last commit 

https://github.com/golismero/openvas_lib/commit/21b2b11fec437acc0f27dc324219c6e4be2f18a3
